#!/bin/bash

# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

BHOJPUR_ARGS="${BHOJPUR_ARGS:-}"
DOCKER_ARGS="${DOCKER_ARGS:---rm}"

_help () {
    echo "Copyright (c) 2018 Bhojpur Consulting Private Limited, India

isomgr remote-exec <package>

Hook into a container where the package was built. Meant to be called inside a
git repository where the Bhojpur ISO specs are.
It uses docker, so you can also set DOCKER_HOST env var, to use a remote host
to pull the docker images.

Example:

$> BHOJPUR_ARGS=... DOCKER_ARGS=... isomgr remote-exec layers/system-x
"
    return 0
}

if [ $# -eq 0 ] ; then
    _help
    exit 1
fi

if [ $1 == "help" ]; then
    _help
    exit 1
fi

IMAGE=$(isomgr tree images --tree $PWD $BHOJPUR_ARGS -o json "$@" | jq -r '.packages[-1].image')

docker run -ti $DOCKER_ARGS $IMAGE