#!/bin/bash

# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -ex

mkdir workdir || true
pushd workdir

IMAGE_NAME="${IMAGE_NAME:-bhojpur_os.img}"
BHOJPUR_PACKAGES="${BHOJPUR_PACKAGES:-}"
BHOJPUR_BIN="${BHOJPUR_BIN:-../isomgr}"
BHOJPUR_CONFIG="${BHOJPUR_CONFIG:-../conf/iso.yaml}"

dd if=/dev/zero of="${IMAGE_NAME}" bs=1MB count=7000

parted "${IMAGE_NAME}" --script -- mklabel msdos
parted "${IMAGE_NAME}" --script -- mkpart primary fat32 0 64
parted "${IMAGE_NAME}" --script -- mkpart primary ext4 64 -1

loopdevice=`losetup -f --show "${IMAGE_NAME}"`
device=`kpartx -va $loopdevice| sed -E 's/.*(loop[0-9])p.*/\1/g' | head -1`
device="/dev/mapper/${device}"
bootp=${device}p1
rootp=${device}p2


mkfs.vfat $bootp
mkfs.ext4 $rootp
mkdir -p root
mount $rootp root

### Chrooting

pushd root
mkdir -p boot
mount $bootp boot

mkdir -p var/lock
mkdir -p var/cache/bhojpur
mkdir -p etc/bhojpur
mkdir -p dev
mkdir -p sys
mkdir -p proc
mkdir -p tmp
mkdir -p dev/pts
cp -rfv "${BHOJPUR_CONFIG}" etc/bhojpur/.iso.yaml
cp -rfv "${BHOJPUR_BIN}" isomgr
sudo mount --bind /dev dev/
sudo mount --bind /sys sys/
sudo mount --bind /proc proc/
sudo mount --bind /dev/pts dev/pts

sudo chroot . /isomgr install -y $BHOJPUR_PACKAGES

# Cleanup/umount
sudo rm -rf isomgr
sudo umount dev/pts
sudo umount dev
sudo umount proc
sudo umount sys
rm -rfv tmp/*
popd

ls -liah root/

umount $bootp
umount $rootp
kpartx -dv $loopdevice
losetup -d $loopdevice

sync

echo "$IMAGE_NAME ready!"
