#!/bin/bash

# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

ALL_KERNELS=$(isomgr search --installed kernel --output json | jq -r '.packages[] | select( .category == "kernel" ) | [.category, .name] | join("/")')
BHOJPUR_KERNEL_PREFIX="${BHOJPUR_KERNEL_PREFIX:-bhojpur}"

BHOJPUR_RELEASE=$(cat /etc/bhojpur/release)
BHOJPUR_TARGET=${BHOJPUR_TARGET:-/}

export BHOJPUR_ISO_NOLOCK=true
generate_micro_initramfs() {
    echo "Generating initramfs and grub setup"

    BOOTDIR=/boot
    CURRENT_KERNEL=$(ls ${BHOJPUR_TARGET}$BOOTDIR/kernel-*)

    # Try to grab current kernel package name, excluding modules
    CURRENT_KERNEL_PACKAGE_NAME=$(isomgr search --installed kernel --output json | jq -r '.packages[] | select( .category == "kernel" ) | select( .name | test("modules") | not).name')
    MINIMAL_NAME="${CURRENT_KERNEL_PACKAGE_NAME/full/minimal}"
    export INITRAMFS_PACKAGES="${INITRAMFS_PACKAGES:-utils/busybox kernel/$MINIMAL_NAME system/bhojpur-init system/bhojpur-live-boot init/bhojpur-skel system/kmod}"

    export KERNEL_GRUB=${CURRENT_KERNEL/${BOOTDIR}/}
    export INITRAMFS=${CURRENT_KERNEL/kernel/initramfs}
    export INITRAMFS_GRUB=${INITRAMFS/${BOOTDIR}/}

    isomgr geninitramfs "${INITRAMFS_PACKAGES}"
    pushd ${BHOJPUR_TARGET}/boot/
    rm -rf Initrd bzImage
    ln -s ${KERNEL_GRUB#/} bzImage
    ln -s ${INITRAMFS_GRUB#/} Initrd
    popd

    mkdir -p ${BHOJPUR_TARGET}/boot/grub

    root=$(cat ${BHOJPUR_TARGET}/boot/grub/grub.cfg | grep -Eo "root=(.*)")
    cat > ${BHOJPUR_TARGET}/boot/grub/grub.cfg << EOF
set default=0
set timeout=10
set gfxmode=auto
set gfxpayload=keep
insmod all_video
insmod gfxterm
menuentry "Bhojpur OS" {
    linux /$KERNEL_GRUB ${root}
    initrd /$INITRAMFS_GRUB
}
EOF

    GRUB_TARGET=
    if [ -e "/sys/firmware/efi" ]; then
        GRUB_TARGET="--target=x86_64-efi --efi-dir=/boot/efi"
    fi
    echo "GRUB_CMDLINE_LINUX_DEFAULT=\"${root}\"" > $BHOJPUR_TARGET/etc/default/grub
    # grub-mkconfig -o /boot/grub/grub.cfg
    install_dev=${root/root=/}
    install_dev=$(printf '%s' "$install_dev" | tr -d '0123456789')
    grub-install ${GRUB_TARGET} $install_dev
}

generate_dracut_initramfs() {
  local kernel=$1
  local md_args="--force"
  local version=""

  echo "Generating initramfs and update grub setup"

  if [ -z "$kernel" ] ; then
    md_args="$md_args --rebuild-all"
  else
    # Retrieve version of the kernel
    if [[ "$kernel" == *lts* ]] ; then
      version=$(isomgr search --installed kernel --output json | jq  ".packages[] | select ( .category == \"kernel\" and .name == \"${BHOJPUR_KERNEL_PREFIX}-lts-modules\" ) | .version")
    else
      version=$(isomgr search --installed kernel --output json | jq  ".packages[] | select ( .category == \"kernel\" and .name == \"${BHOJPUR_KERNEL_PREFIX}-modules\" ) | .version")
    fi
    version=${version%\+*}
    md_args="$md_args -r ${version}"
  fi

  bhojpur-dracut $md_args

  # TODO: Fix initialization of bzImage, Initrd. Is it used correctly?

  grub-mkconfig -o ${BHOJPUR_TARGET}/boot/grub/grub.cfg
}


cat <<'EOF'
   .       | 
 +  :      |
           :      ___
    .  .   |   ' ((_))
          ,|.' 
---------(-O-`---------
         ,`|'`.
       ,   |    .
      ,    :       :  " 
     ,     |     --+--
..:        |       !
EOF

case "$BHOJPUR_RELEASE" in
  "micro")
    if [ $# -eq 0 ]; then
        echo "Generating only initramfs"
    else
        isomgr replace --nodeps $ALL_KERNELS --for "$1" --for "${1/full/}"modules
    fi
    generate_micro_initramfs
    ;;
  "micro-embedded"|"desktop-embedded")
    if [ $# -eq 0 ]; then
        echo "Nothing to do"
    else
        isomgr replace --nodeps $ALL_KERNELS --for "$1" --for "${1/full/}"modules --for "${1/full/}"initramfs
    fi
    ;;
  "desktop")
    if [ $# -eq 0 ]; then
        echo "Generating only the initramfs image of all available kernels."

    else
        isomgr replace --nodeps $ALL_KERNELS --for "$1" --for "${1/full/}"modules
    fi
    generate_dracut_initramfs
    ;;
  *)
    echo "The release $BHOJPUR_RELEASE is unsupported."
    exit 1
    ;;
esac

exit 0